export class NewUrlConfig {
    public static EndPoint = {
        Intake: {
            GetNextNumberUrl: `Nextnumbers/getNextNumber?apptype=IntakeNumber`,
            ServiceRequestIncidentTypeUrl: `manage/Servicerequestincidenttype?filter={"where" :{"activeflag":1}}`,
            IntakeServiceRequestIllegalActivityTypeUrl: `Intakeservicerequestillegalactivitytypes?filter={"where" :{"activeflag":1}}`,
            IntakeServiceRequestInputTypeUrl: `Intakeservicerequestinputtypes?filter={"where" :{"activeflag":1}}`,
            GlobalPersonSearchUrl: 'globalpersonsearches/getPersonSearchData',
            InvolvedEnititesSearchUrl: 'gloabalagencysearches/getAgencySearchData',
            AgencyCategoryUrl: 'admin/agencycategory',
            CountryListUrl: 'admin/county/list',
            StateListUrl: 'States',
            MaritalStatusUrl: 'admin/maritalstatustype',
            ReligionTypeUrl: 'admin/religiontype',
            RegionListUrl: 'admin/region/list',
            NextnumbersUrl: 'Nextnumbers/getNextNumber?apptype=servicerequestauthorizationnumber',
            DADispositionUrl: 'admin/intakeservicerequesttype/listdadisposition',
            DAStatusUrl: 'admin/intakeservicerequesttype/listdastatus',
            AllegationsIndicaorUrl: 'admin/allegation/getallegationsandindicaors',
            DATypeUrl: 'admin/intakeservicerequesttype',
            EthnicGroupTypeUrl: 'admin/ethnicgrouptype',
            GenderTypeUrl: 'admin/gendertype',
            LivingArrangementTypeUrl: 'admin/livingarrangementtype',
            LanguageTypeUrl: 'admin/languagetype',
            RaceTypeUrl: 'admin/racetype',
            RelationshipTypesUrl: 'Relationshiptypes',
            ActorTypeUrl: 'admin/actortype',
            IntakeserviceRequestCrossReferenceReasonTypesUrl: 'Intakeservicerequestcrossreferencereasontypes',
            ServiceRequestSearchesUrl: 'servicerequestsearches/getDetails',
            SameRACrossRefDAsUrl: 'GetSameRACrossRefDAs/getDetails',
            ProgressNoteURL: 'admin/progressnotetype/listprognotetypes',
            ProgressNoteSubTypeUrl: 'admin/progressnotetype/listprognotesubtypes',
            IntakeServiceRouteDAUrl: 'Intakeservicerequests/routeda',
            SendtoSupervisorreviewUrl: 'Intakedastagings/reviewIntake',
            PersonRelativeUrl: 'personrelations',
            PersonAddressesUrl: 'personaddresses',
            TemporarySavedIntakeUrl: 'Intakedastagings',
            CompleteIntakeUrl: 'Intakedastagings/completeIntake',
            IntakeServiceRequestsUrl: 'Intakeservicerequests/getdsdsactions',
            MyIntakeListUrl: 'Intakedastagings/listintakeda',
            PersonUrl: 'People/getwholepersondetials',
            GetIntakeAssessmentUrl: 'admin/assessmenttemplate/getlist',
            ValidateAddressUrl: 'people/validateaddress',
            CommunicationUrl: 'Intakeservicerequestinputsources?filter={}',
            SuggestAddressUrl: 'people/suggestaddress',
            IntakePurposes: 'Intakeservicerequestpurposes',
            IntakeAgencies: 'admin/teamtype/list?filter={}',
            Intakeservs: 'Intakeservs',
            ResourceTooltipUrl: 'resources/resourcelist',
            AttachmentGridUrl: 'Documentproperties/getintakeattachments',
            SaveAttachmentUrl: 'Documentproperties/addintakeattchment',
            DeleteAttachmentUrl: 'Documentproperties/delete',
            PersonInvolvedManageUrl: 'People/intakeperson',
            AddressTypeUrl: 'admin/personaddresstype',
            MDCountryListUrl: 'admin/county',
            OffenceCategoryListUrl: 'offensecategories',
            PhoneTypeUrl: 'admin/personphonetype',
            EmailTypeUrl: 'admin/personemailtype',
            saveIntakeUrl: 'Intakedastagings/listdadetails'
            
        },
        DSDSAction: {
            Attachment: {
                UploadAttachmentUrl: 'attachments/uploadsFile',
                AttachmentGridUrl: 'Documentproperties/getattachments',
                AttachmentUploadUrl: 'attachments/uploadsFile',
                AttachmentTypeUrl: 'Intake/attachmenttype',
                AttachmentClassificationTypeUrl: 'Intake/attachmentclassificationtype',
                SaveAttachmentUrl: 'Documentproperties/addattchment'
            },
            Disposition: {
                StatusUrl: 'Intakeservicerequests/statuslist',
                DispositionUrl: 'Intakeservicerequests/dispositionlist',
                DispositionListUrl: 'Intakeservicerequestdispositioncodes/GetDispositon',
                DispositionAddUrl: 'Intakeservicerequestdispositioncodes/Add'
            }
        }
    };
}
